### PR TITLE
Background theory

### PR DESCRIPTION
**Pull request by BlaviButcher**
Finished up all the skeleton content for the Background Theory category. The later entries are a bit simpler as I was trying to tone down the details so we just had something to work from.
I've left only headings for the Matrix Operations as I'm not sure if it'll get into the too complex side. Besides that I'd like to use latex to show how that's done.
I've got a couple of screenshots of doodles I've done just as a reference for something we could have there using digital media.
There some reference to Dominance Genetic Relationships and Epistasis Genetic Relationships in Larry Schaeffer's notes, but he did mention that they are usually irrelevant when it comes to genetic evaluation.

### CODE REVIEW

**Comment by dpgarrick** [comment]
The latex doesn't seem to be working, will have a comb through the rest sometime later when I have some time.

**Comment by BlaviButcher** [comment]
> The latex doesn't seem to be working, will have a review in more detail of the rest sometime later when I have some time.

I had a chat to Joel about that the other day. He got everything sorted and there's PR there #18 that sorts that out.

**Comment by dpgarrick** [comment]
Whoopsie! Merged to main. Can you merge main into here so we can check it works?

**Comment by BlaviButcher** [comment]
> Whoopsie! Merged to main. Can you merge main into here so we can check it works?

Sweet, all sorted. Looks good!

**Pull request merged**
