### PR TITLE
basic skeleton - feel free to rename things

### PR DESCRIPTION
**Pull request by BlaviButcher**
Wanted to get a basic skeleton out so we could start a discussion of where bits will fit in. I'll add the data I have so far and update the svgs after this pull

### CODE REVIEW

**Comment by jhwz** [comment]
Looks all good to me

**Comment by dpgarrick** [comment]
Feels like the intended audience is a bit unclear at the moment.

Let's try partition the super-headings into:
* "Background Theory" for all the bare fundamental type notes - Statistics, Genetics, Matrices (rename to Linear Algebra) go here
* "Analysis" for specifics about models and non-additive genetic effects, phantom groups can be moved from "Genetics" to here
* "Interpretation" (instead of "In Practice")
* "Technical" - I think all command line and related sections should go under here (Linux/Git/Helical tools/etc)

**Comment by rchandco** [comment]
Is there a way to view the MR in the "live" format?

I don't like having the word "basic" in there, as for someone new thats a bit daunting! Something like "Introduction to genetics" might be better :)

Otherwise, what @dpgarrick has suggested sounds good!

**Comment by jhwz** [comment]
> Is there a way to view the MR in the "live" format?

Hmm actually there should be, but for some reason it hasn't worked for this MR.

Try visiting https://directory-skeleton.docs-5gm.pages.dev/ to see the preview

**Comment by dpgarrick** [comment]
There is a preview here https://8b80ec26.docs-5gm.pages.dev/

You have to click "Show all checks" then "Details" for Cloudflare pages to see the link - its a bit sneaky!

**Comment by BlaviButcher** [comment]
> Is there a way to view the MR in the "live" format?
> 
> I don't like having the word "basic" in there, as for someone new thats a bit daunting! Something like "Introduction to genetics" might be better :)
> 
> Otherwise, what @dpgarrick has suggested sounds good!

Thanks for the feedback! I'll make those changes. Yea, I had issues finding it the link as well. Down the bottom there's the "All checks have passed" bit. To the right is a link "Show all checks" which will drop down cloudflare pages and the link should be in the details.

**Comment by BlaviButcher** [comment]
> Feels like the intended audience is a bit unclear at the moment.
> 
> Let's try partition the super-headings into:
> 
> * "Background Theory" for all the bare fundamental type notes - Statistics, Genetics, Matrices (rename to Linear Algebra) go here
> * "Analysis" for specifics about models and non-additive genetic effects, phantom groups can be moved from "Genetics" to here
> * "Interpretation" (instead of "In Practice")
> * "Technical" - I think all command line and related sections should go under here (Linux/Git/Helical tools/etc)

Thanks for the feedback Dan. That seems a lot clearer.

**Comment by dpgarrick** [comment]
Looks good!

**Pull request merged**
